### ISSUE TITLE
Use with Openshift ?

### ISSUE THREAD

**Issue by stujb** [jpbetz/auger#10]
Would it be possible to use auger on Openshift objects such as Builds, BuildConfigs, DeploymentConfigs etc ?

If I try to decode I get the following error: 
` cat test.data | auger decode
Error: error decoding from application/vnd.kubernetes.storagebinary: no kind "Build" is registered for version "v1"
`

**Comment by jpbetz** [comment]
No plans to add direct support for openshift.  But there is a `--raw`flag (`auger extract -f <db-file> --key <desired-key> --raw`) that could be used go get the data value out. This could then be passed into a openshift specific tool to decode or interpret further.
