### ISSUE TITLE
README.md should talk about how to install the software

### ISSUE THREAD

**Issue by indrayam** [jpbetz/auger#7]
Hi there!

Since I am not very well versed with go, as much as I would love to use this software, I have no idea how. I first tried:

`go get github.com/jpbetz/auger`

which gave me this error message:

```
# cd .; git clone https://github.com/kubernetes-incubator/auger /Users/anasharm/workspace/go-apps/src/github.com/kubernetes-incubator/auger
Cloning into '/Users/anasharm/workspace/go-apps/src/github.com/kubernetes-incubator/auger'...
remote: Repository not found.
fatal: repository 'https://github.com/kubernetes-incubator/auger/' not found
package github.com/kubernetes-incubator/auger/cmd: exit status 128
```

I cloned the repo. Tried running the following:

```
make build
```

and it gave this error:

```
ARCH=amd64 go build -o build/auger
main.go:22:2: cannot find package "github.com/kubernetes-incubator/auger/cmd" in any of:
	/usr/local/Cellar/go/1.9.4/libexec/src/github.com/kubernetes-incubator/auger/cmd (from $GOROOT)
	/Users/anasharm/workspace/go-apps/src/github.com/kubernetes-incubator/auger/cmd (from $GOPATH)
make: *** [build] Error 1
```

Sure would be nice to add a section in README.md that talks about how to install this software. I will be happy to do it, and open a PR, if I knew how to make it work :wink:

**Comment by warmchang** [comment]
git clone https://github.com/jpbetz/auger /go/src/github.com/kubernetes-incubator/auger
cd /go/src/github.com/kubernetes-incubator/auger
glide install -v
go install -v github.com/kubernetes-incubator/auger
chmod +x /go/bin/auger

**Comment by hellobinge** [comment]
check out the Makefile

if you have docker installed on your machine, then you can just use "make release".
the auger binary file will be installed at /angur/build/auger

xD

**Comment by indrayam** [comment]
> @indrayam ,
> 
> ```
> # git clone https://github.com/jpbetz/auger /go/src/github.com/kubernetes-incubator/auger
> # cd /go/src/github.com/kubernetes-incubator/auger
> # glide install -v
> # go install -v github.com/kubernetes-incubator/auger
> # chmod +x /go/bin/auger
> ```

Thanks for the inputs @warmchang I decided to document the steps I went through to make the thing work:

https://github.com/indrayam/nerd-notes/blob/master/compute-orchestrators/kubectl.md#take-a-peek-inside-etcd

**Comment by jpbetz** [comment]
Thanks for pointing this out. I've documented the minimal steps in the readme: https://github.com/jpbetz/auger/pull/15
